### ISSUE TITLE
Modbus Bridge stopped compiling with ESPHome 2025.11.2

### ISSUE THREAD

**Issue by seppelw** [Pluimvee/esphome-modbus-tcp-to-rtu#1]
Modbus Brdige fails to compile with ESPHome 2025.11.2.

`Compiling .pioenvs/heidelbergmodbus/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
In file included from src/esphome/core/component.h:8,
                 from src/esphome/components/modbus_bridge/modbus_bridge.h:3,
                 from src/esphome/components/modbus_bridge/modbus_bridge.cpp:1:
src/esphome/components/modbus_bridge/modbus_bridge.cpp: In member function 'virtual void ModBusBridgeComponent::dump_config()':
src/esphome/components/modbus_bridge/modbus_bridge.cpp:43:80: error: request for member 'c_str' in 'esphome::network::get_use_address()', which is of non-class type 'const char*'
   43 |     ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address().c_str(), this->port_);
      |                                                                                ^~~~~
src/esphome/core/log.h:101:101: note: in definition of macro 'esph_log_config'
  101 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/modbus_bridge/modbus_bridge.cpp:43:5: note: in expansion of macro 'ESP_LOGCONFIG'
   43 |     ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address().c_str(), this->port_);
      |     ^~~~~~~~~~~~~
*** [.pioenvs/heidelbergmodbus/src/esphome/components/modbus_bridge/modbus_bridge.cpp.o] Error 1
========================= [FAILED] Took 153.15 seconds =========================`

**Comment by seppelw** [comment]
#2

**Comment by seppelw** [comment]
Temporay fixe also stoped compiling. rebuild function for 2026.2

**Comment by Pluimvee** [comment]
Major silent breaking changes in socket.h implementation causing the code to stop working in ESPHome framework. Its resolved in the latest version.

Thanks for notifying!!
